[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fireducks>=1.2.5",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "psutil>=7.0.0",
]
